title:              Breen Blog
email:              conor@breen.ie
description:        Want to see me make a to-do app? Me neither
author:             Conor Breen
baseurl:            ""
url:                "https://breen.ie"

# Social Profiles
twitter_username:
github_username:    conorbr
facebook_username:
instagram_username: insta.breen
linkedin_username:  conor-breen

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-cayman